const Map<String, String> technicalLabels = {
  'arrival_date': 'Fecha de llegada',
  'created_at': 'Fecha de registro',
  'clients': 'Clientes',
  'reasons': 'Motivos',
  'copilots': 'Copilotos',
  'driver': 'Conductor',
  'plate': 'Placa',
  'origin': 'Origen',
  'destination': 'Destino',
  'observations': 'Observaciones',
  'created_by': 'Creado por',
  'destiny': 'Destino',
  'exit_date': 'Fecha de salida',
  'exit_point': 'Punto de salida',
  'final_gasoline_name': 'Combustible salida',
  'initial_gasoline_name': 'Combustible inicial',
  'initial_km': 'Km inicial',
  'license_name': 'Matrícula',
  'final_km': 'Km final',
  'license': 'Matrícula',
  'name_driver': 'Conductor',
  'name_gasoline_initial': 'Combustible inicial',
  'name_gasoline_final': 'Combustible final',
};